### ISSUE TITLE
Could you please use resolve default config path relative to `$XDG_CONFIG_HOME`?

### ISSUE THREAD

**Issue by ironhouzi** [Lallassu/gorss#2] opened 2019-09-19 06:01 UTC
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

I'd make a PR, but I've never written a single line of Go in my life. I'd be afraid I'd just commit non-idiomatic code.

**Comment by prologic** [comment] 2019-09-19 06:12
There's probably a library for this somewhere if you search Github by `language:Go`. Put up a PR I'll help you get it into Idiomatic Go :D No better time to learn!

**Comment by Lallassu** [comment] 2019-09-19 06:26
Sounds like a good addition. I will take a look at it.

**Comment by Lallassu** [comment] 2019-09-19 17:29
I've fixed this in the latest commit to master.

It first checks if you use command line arguments (-config -theme -db), if they are the default ones it checks for XDG configuration directories. It will also create the XDG configuration directory for the application (gorss). 

The database will automatically be created in the "<DataHome>/gorss". The default.theme and gorss.conf must be placed in the "<configHome>/gorss" to be used.

Hope this helps, feel free to give it a try. I've only tried it on OSX and it seemed to work as expected.

**Comment by ironhouzi** [comment] 2019-09-20 07:54
```
panic: runtime error: integer divide by zero [recovered]
        panic: runtime error: integer divide by zero

goroutine 1 [running]:
github.com/rivo/tview.(*Application).Run.func1(0xc0000ea400)
        /Users/nergal/go/pkg/mod/github.com/rivo/tview@v0.0.0-20190829161255-f8bc69b90341/application.go:149 +0x82
panic(0x95d3e0, 0xf9bf40)
        /usr/local/Cellar/go/1.13/libexec/src/runtime/panic.go:679 +0x1b2
github.com/rivo/tview.(*Flex).Draw(0xc000170420, 0xa95b00, 0xc00039efc0)
        /Users/nergal/go/pkg/mod/github.com/rivo/tview@v0.0.0-20190829161255-f8bc69b90341/flex.go:152 +0x3ae
github.com/rivo/tview.(*Flex).Draw(0xc0001704b0, 0xa95b00, 0xc00039efc0)
        /Users/nergal/go/pkg/mod/github.com/rivo/tview@v0.0.0-20190829161255-f8bc69b90341/flex.go:173 +0x347
github.com/rivo/tview.(*Flex).Draw(0xc000170540, 0xa95b00, 0xc00039efc0)
        /Users/nergal/go/pkg/mod/github.com/rivo/tview@v0.0.0-20190829161255-f8bc69b90341/flex.go:173 +0x347
github.com/rivo/tview.(*Application).draw(0xc0000ea400, 0x0)
        /Users/nergal/go/pkg/mod/github.com/rivo/tview@v0.0.0-20190829161255-f8bc69b90341/application.go:363 +0xff
github.com/rivo/tview.(*Application).Run(0xc0000ea400, 0x0, 0x0)
        /Users/nergal/go/pkg/mod/github.com/rivo/tview@v0.0.0-20190829161255-f8bc69b90341/application.go:155 +0xb4
main.(*Window).Start(0xc0000ea300)
        /Users/nergal/Dropbox/dev/gorss/src/window.go:167 +0x83
main.(*Controller).Init(0xc000022d80, 0xc00002a270, 0x25, 0xc00002a300, 0x28, 0xc00002a390, 0x28)
        /Users/nergal/Dropbox/dev/gorss/src/controller.go:68 +0x403
main.main()
        /Users/nergal/Dropbox/dev/gorss/src/main.go:73 +0x58d
```

**Comment by Lallassu** [comment] 2019-09-20 07:59
@ironhouzi is that from the latest master? I had some issues that I fixed yesterday. And the configuration has been updated as well, to handle sizing of the windows. I might suspect that you use an old configuration with later version of the binary perhaps?

It could be caused by these settings are missing. These settings let you specify sizing ratios for the different windows(flex boxes) in the application.
```
 "feedWindowSizeRatio": 2,
    "articlePreviewWindowSizeRatio": 5,
    "articleWindowSizeRatio": 2,
    "previewWindowSizeRatio": 1,
```

**Comment by ironhouzi** [comment] 2019-09-20 08:25
Yes, I was using an old config. That resolved the issue. Thank you so much!

BTW, is there a way to bundle the default config files into `$XDG_DATA_DIR` and fallback to default if nothing is specified?

It would simplify the install process and make sure a correctly versioned default config is always available. This seems to be a common UNIX pattern, having a default config bundled with the application.

**Comment by prologic** [comment] 2019-09-20 08:33
> It would simplify the install process and make sure a correctly versioned default config is always available. This seems to be a common UNIX pattern, having a default config bundled with the application.

Isn't the UNIX principle that a program take as few options as possible to accomplish its task with options/flags taking sensible defaults?

> I would also look into using github's "releases" page to place compiled binary files. Your git repo will probably explode in size if you're planning to commit binary files every time you release.

+1 Yes! I notice you have committed binary files in [./bin](/bin) -- Use Github releases instead! I recommend using [goreleaser](https://github.com/goreleaser/goreleaser)

**Comment by Lallassu** [comment] 2019-09-20 08:37
> > I would also look into using github's "releases" page to place compiled binary files. Your git repo will probably explode in size if you're planning to commit binary files every time you release.
> 
> +1 Yes! I notice you have committed binary files in [./bin](/bin) -- Use Github releases instead! I recommend using [goreleaser](https://github.com/goreleaser/goreleaser)


yes! Good point, I've just added this as a fast way of getting it up running for people with no Go experience. But you are absolutely right, I will change to releases :)

Regarding the configuration, I think it will be easier to handle if I start having some bundle or installation packages. Not sure how I will do this yet.

I will push a new updated version later today since I found a couple of bugs. And that will also add some stuff to the configuration file. So I guess some sort of configuration migration would be nice to have in the future as well.

**Comment by Lallassu** [comment] 2019-09-23 12:12
I've changed to put the binaries bundled with config + themes on the release page.

**Closed by Lallassu** 2019-09-23 12:12 UTC
Labels: enhancement
